### ISSUE TITLE
ECharts integration success

### ISSUE THREAD

**Issue by helgasoft** [julianna-langston/chart2music#147]
Great package, easy to work with 🥇
Noticed your [recent post](https://github.com/apache/echarts/issues/18256) on the ECharts board and got intrigued.  ECharts currently does not support keyboard commands.
But _chart2music_ does!  So I played with two of your examples and got it rocking - [**chart2music on ECharts**](https://codepen.io/helgasoft/pen/YzOymwZ).
Custom **hotkeys** is a nice feature. I added **'+'** and **'-'** for zoom in & out. It could help with EChart issues like [this one](https://github.com/apache/echarts/issues/18280).
Hope many more people will benefit from your work. Thank you.

![image](https://user-images.githubusercontent.com/13038071/220029698-ac1b3f19-42fb-4810-b7c1-edbd48f4c6d0.png)

**Comment by spmealin** [comment]
Thank you for the kind words, we’re so glad you like C2M. If you have any questions, comments, feature requests, or anything else, please feel free to open an issue.
