### ISSUE TITLE
New Feature: Audio Engine: Resonance

### ISSUE THREAD

**Issue by julianna-ciq** [julianna-langston/chart2music#172]
Expand the `playDataPoint` function to include a resonance value. `resonance` will be a number between 0 and 1, indicating a percent of the maximum amount of resonance that can be played. By default, the value is 0.

When this is included, the data point should have resonance/reverb/echo-y version of the data point being played. This will be used in bubble plots and area bar charts to represent the volume of the data point.

We expect users to get rough, estimated vibes from this sonification. We want users to be able to tell if something is "a lot", "a little", or "a medium amount". The user does not need to be able to distinguish small differences between data points.

**Comment by spmealin** [comment]
Resonance appears to be non-trivial to implement with pure Web Audio API. I also question if this feature as designed will work as well as hoped. 

I’m going to close this for now for the above reasons. Once we receive a feature request for bubble charts or the like, we can reexamine the design.
