### ISSUE TITLE
Suggestion: appending sonify instruction to original alt text when available

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#19]
Currently, when `alt` attribute and its corresponding value exist within an image  element, c2m does not add any sonification instruction message. What if you append the sonification instruction to the original alt value by its default behavior, and make its behavior configurable for the users (e.g., options for append, override, none)?

## Reproducible Example

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.jsdelivr.net/npm/chart2music"></script>
</head>

<body>

    <img src="mychart.png" id="MyChart" alt="Original alt text by content author." />

    <script>
        c2mChart({
            type: "bar",
            element: document.getElementById("MyChart"),
            data: [1, 2, 3]
        });
    </script>
</body>

</html>
```

**Comment by julianna-ciq** [comment]
I'm going to need to look into the implications of that some more. For your use case, I'd recommend adding a div element like this:
```html
<div id="caption"></div>
```

and updating your c2mChart call to include this property:
```js
cc: document.getElementById("caption")
```

This way, you would get instructions and additional information as you focus on the chart, as well as interacting with it.

In summary, your reproducible example would be updated to this:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.jsdelivr.net/npm/chart2music"></script>
</head>

<body>

    <img src="mychart.png" id="MyChart" alt="Original alt text by content author." />

    <script>
        c2mChart({
            type: "bar",
            element: document.getElementById("MyChart"),
            data: [1, 2, 3]
        });
    </script>
</body>

</html>
```

**Comment by jooyoungseo** [comment]
Thanks! @julianna-ciq , but the updated example is still the same as the original one. Your updated example would be greatly appreciated at your best convenience.

**Comment by julianna-ciq** [comment]
Edited the previous post. Sorry about that

**Comment by julianna-ciq** [comment]
@jooyoungseo Does the updated example work for you?

**Comment by jooyoungseo** [comment]
Thanks! This works nicely!
