### ISSUE TITLE
Proposal: Add i18n + some translations.

### ISSUE THREAD

**Issue by ayjayt** [julianna-langston/chart2music#370]
Caption box is currently in english.

If it's amenable to you, I would be willing to add international support and could provide translations in german and spanish!

Would want approval before I start the work, it would be done over the course of months.

**Comment by julianna-langston** [comment]
Thank you for your interest! I just merged in a PR to add i18n support to the library. We use formatjs for i18n, and the language is in ICU message format.

The language file for english is here:
https://github.com/julianna-langston/chart2music/blob/main/src/translations/en.ts

If you want to translate some or all of the text strings into another language, you can
1. Copy the en.ts file. Rename the copied file to something like "de.ts" for german.
2. Add the new file to the translations index page, here: https://github.com/julianna-langston/chart2music/blob/main/src/translations/index.ts

Any lines that don't get translated will fall back to the english text.

We'd be happy for any amount of help you're willing to provide. If you have any other questions, please let us know!

**Comment by ayjayt** [comment]
Cool! Spanish starting on Tuesday, German starts when that's done.

**Comment by ayjayt** [comment]
[@ploperav](https://github.com/ploperav) said she'd have it (spanish) done  by the weekend :-)

**Comment by ayjayt** [comment]
First spanish is up https://github.com/julianna-langston/chart2music/pull/383

Confidence on German seems low, unfortunately.

**Comment by Neo-Oli** [comment]
Hi, we at the @swissredcross are very much interested on this tool for our chart.js charts. We would be able to provide professional translations for (at least) German, French and Italian, if it would be implemented and added to chart2music and chartjs2music.

**Comment by julianna-langston** [comment]
@Neo-Oli We'd love to have your translations! Once we have spanish merged in (https://github.com/julianna-langston/chart2music/pull/383), we'll ship a release of both chart2music and chartjs2music.

Feel free to open a PR with translations, and we'd love to take a look. If you have any questions, let me know!

**Comment by Neo-Oli** [comment]
Just an update. I finally managed to correctly initiate a translation order for our translation team (not something I normally do). So the translations for German, French and Italian should hopefully be done in one or two weeks.

**Comment by Neo-Oli** [comment]
Et voilà! 
German, French and Italian translations are here: #402 #403 #404

**Comment by julianna-langston** [comment]
@Neo-Oli Thanks for the translations! I've updated Chart2Music, so those translations are now live in v1.15.1.

I've also updated chartjs-plugin-chart2music to use v1.15.1, so your translations are now available in its v0.4.0.

Please let me know if you have any issues!
