### ISSUE TITLE
Node engine version support

### ISSUE THREAD

**Issue by dakota-kallas** [julianna-langston/chart2music#455]
Is there a specific reason why this plugin doesn't support node engine version `16.14`? If not, is support for it able to be added?

![image](https://github.com/julianna-langston/chart2music/assets/79180508/aa68f5c1-babe-420e-b059-adf75257913d)

**Comment by julianna-langston** [comment]
Thank you for bringing this to our attention. We set the engine requirement back when we used Docusaurus, about a year or 2 ago. When we removed Docusaurus, we forgot to remove the engine requirement.

This requirement has now been removed, and that change is live in 1.16.3. I hope that helps!

Please let us know if you encounter any other issues.
