### ISSUE TITLE
Mobile device support

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#50]
I was wondering if C2M sonification could be also access via mobile devices, such as iOS and Android. My quick test with iPhone does not seem to work, but please correct me if I am wrong.

**Comment by julianna-ciq** [comment]
We have preliminary support for mobile interactions. Here is what you can do:

1. Open a chart in a browser on a mobile device.
2. Find the chart on the screen.
3. Over the chart, initiate a pass-through gesture. For iOS, this means double tap and hold until you hear 3 rising tones. I don't know what that would be on Android.
4. Using one finger, swipe right. This will move focus to the next data point.
5. Perform the pass-through gesture, then use 2 fingers to swipe right. This will play all of the data through to the end.
6. If the chart has multiple categories, perform the pass-through gesture, then use 2 fingers to swipe down. This will move focus to the next category.
7. If the chart has multiple statistics (such as in a OHLC), perform the pass-through gesture, then use 1 finger to swipe down. This will move focus to the next statistic.

I'll create an issue for writing a user guide for interacting with charts.

**Comment by jooyoungseo** [comment]
Thanks, @julianna-ciq ! I have tested again on iPhone following your instruction. Unfortunately, it does not work on my end (tested with both Safari and Chrome). I hear tripple rising tone with the single double tap, but it does not seem to bypass the next VO gesture (e.g., swipe right). [This related post](https://www.applevis.com/forum/ios-ipados/how-pass-through-voiceover-gesture-system-gesture) similarly discusses this issue.

**Comment by spmealin** [comment]
I’m pretty sure mobile device support is not currently available due to restrictions on the iPhone and the number of interactions required to interact with all the charts that we currently handle. Please let me know if I’m wrong about this, @julianna-langston.

I’m keeping this issue open for now for any discussion or design ideas, but I am removing this from our internal roadmap until we can resolve some of the design questions.

**Comment by spmealin** [comment]
Because we still do not have a UX model that covers all of the essential features on mobile devices, I am closing this issue. If more people come and open up additional issues for mobile device support, we can revisit it then.
