### ISSUE TITLE
Add candlestick chart example

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#53]
Please correct me if I am wrong, but there does not seem to be a candlestick chart example. It would be great if a sample chart could be added.

**Comment by julianna-ciq** [comment]
Do you mean in the examples repo, or in codepen?

In the examples folder, the D3 example is a candlestick.

You can interact with it if you:
1. Clone the repo and run `npm install`
2. Run `npm run start`
3. Open your browser to `localhost:8080/examples/d3.html`

The only D3 example is a candlestick plot.

**Comment by julianna-ciq** [comment]
In case you wanted a codepen example, I have created one:

[Candlestick example on CodePen](https://codepen.io/chart2music/full/rNvqBYL)

**Comment by jooyoungseo** [comment]
Aw, great! I did not know that the candlestick was included in the example folder because its file name (D3 ) was not providing that chart type info. Could you please rename the file name in the example folder to be self-expalnatory? Thanks for the codepen example as well.

**Comment by julianna-ciq** [comment]
I've renamed the example file d3.html to d3_candlestick.html
