### ISSUE TITLE
Update the help dialog to be more helpful and extensible

### ISSUE THREAD

**Issue by spmealin** [julianna-langston/chart2music#587]
The help dialog (accessed by pressing the H key when focused on a chart) should be updated to be more helpful for end-users and extensible for C2M integrators. To accomplish these goals, the following changes should be made:

* Divide the dialog into three sections: the help text, the keyboard shortcut listing, and the help footer.
* For both the help text and keyboard shortcut listing, we should provide intercept functions to allow developers using C2M to modify the default text.
* The help footer should not be modifiable since it links to more help information on the C2M main site.
* All of the above should be I18N aware.

The below should be the default values for the three sections.

Help text:

> You can use the below keyboard shortcuts to navigate this chart more quickly. Please note, on some computers, the keys that you need to press may be called something else than what is listed below or may be emulated by a combination of keys. For example, on Apple keyboards without a physical home key, you can press the function key and the left arrow key at the same time to perform the same action. When possible, common alternate keyboard shortcuts will be provided in the below table.

Keyboard shortcut listing:

| Keyboard Shortcut | Description | Common Alternate Keyboard Shortcut |
| ---------- | ---------- | ---------- |
| Move to next point | Right arrow |           |
| Move to previous point | Left arrow |            |
| Move to left-most point | Home | Function + Left arrow |
| Move to right-most point | End | Function + Right arrow |
| Play to right edge of chart | Shift + End | Shift + Function + Right arrow |
| Play to left edge of chart | Shift + Home | Shift + Function + Left arrow |
| Stop play | Control |            |
| Increase playback speed | Q |            |
| Decrease playback speed | E |            |
| Replay current point | Spacebar |            |
| Select point | Enter |            |
| Move right by a tenth | Control + Right arrow |            |
| Move Left by a tenth | Control + Left arrow |            |
| Move to next statistic | Down arrow |            |
| Move to previous statistic | Up arrow |            |
| Move to next group | Page down | Function + Down arrow |
| Move to previous group | Page up | Function + Up arrow |
| Move to first group | Alt + Page up | Option + Function + Up arrow |
| Move to last group | Alt + Page down | Option + Function + Down arrow |
| Play through all next groups | Shift + Page down | Shift + Function + Down arrow |
| Play through all previous groups | Shift + Page up | Shift + Function + Up arrow |
| Move to group minimum value | [ |            |
| Move to group maximum value | ] |            |
| Move to chart minimum value | Control + [ |            |
| Move to chart maximum value | Control + ] |            |
| Toggle monitor mode | M |            |
| Open help dialog | H |            |
| Open options dialog | O |            |

The default footer:

> For information on making charts accessible and additional help, please visit www.chart2music.com.

Below are the function signatures for the intercept functions. These are approximately in TypeScript prototype format. The function name capitalization and name of function arguments should follow best practices for the language/library:

```
function ModifyHelpDialogText (lang: string, text: string) -> string
```

```
function ModifyHelpDialogKeyboardListing (lang: string, headers: array, shortcuts: array) -> array
```

For the ModifyHelpDialogKeyboardListing function, the default headers argument should look like the below:

```
headers = ["Keyboard Shortcut", "Description", "Common Alternate Keyboard Shortcut"]
```

For the ModifyHelpDialogKeyboardListing function, the shortcut argument and return values should be the same array shape. The default shortcut value should look like the below:

```
shortcut = [
    ["Move to next point", "Right arrow", ""],
    ["Move to previous point", "Left arrow", ""],
    …etc…
    ["Play to right edge of chart", "Shift + End", "Shift + Function + Right arrow"]
    …etc…
]
```

**Comment by julianna-langston** [comment]
This feature as described does not provide developers the ability to modify the headers. Should that be included?

**Comment by spmealin** [comment]
Yes, apologies. The return type for the ModifyHelpDialogKeyboardListing intercept function should have the headers prefixed as the first row.

```
return [
    ["Keyboard Shortcut", "Description", "Common Alternate Keyboard Shortcut"],
    ["Move to next point", "Right arrow", ""],
    ["Move to previous point", "Left arrow", ""],
    …etc…
    ["Play to right edge of chart", "Shift + End", "Shift + Function + Right arrow"]
    …etc…
]
```

Note that means that the shape of the shortcut argument and the return value are slightly different. The return value does require the headers to be the first row, while the shortcut parameter does not include the headers.

There should also be a check to ensure that the length of the headers row and the lengths of the data rows are consistent.
