### ISSUE TITLE
Suggestions for heatmaps and correlation matrices

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#64]
I appreciate the new support for heatmaps and correlation matrices. I would like to open a discussion for the following items:

- [ ] Add a vertical autoplay feature.

Horizontal autoplay is possible with ctrl+shift+left/right arrows; there is no way to autoswipe cells in a vertical direction.

- [ ] Consider up/down arrows to jump between different rows.

I understand that you borrowed the same concepts using pg-up/down keys from multi-line charts and grouped box plot. Given that heatmaps and matrices are grid form and well-mapped with standard arrow key layout, wouldn't it be more cognitively accessible and easier to press? In heatmap consisting of two categorical variables, both horizontal and vertical navigations are changing groups anyway. I think there is no strong reason to keep using pg up/down keys only for vertical nav given this characteristic.

**Comment by julianna-ciq** [comment]
As of 1.6.2, you can use the up and down arrow keys to navigate between rows on heatmaps and matrices.

You can achieve vertical autoplay with Shift+PageUp and Shift+PageDown.
